### ISSUE TITLE
Check if the shift depends on h, ns and omega b 

### ISSUE THREAD

**Issue by Justinezgh** [DifferentiableUniverseInitiative/sbi_lens#30]

**Comment by dlanzieri** [comment]
In the following table, I computed the fractional differences between the shift parameters, i.e I computed the shift at +/- 3sigma from the fiducial value divided by the shift at the fiducial. 
<img width="605" alt="Screenshot 2023-04-07 alle 19 03 57" src="https://user-images.githubusercontent.com/72620117/230737759-c43795ed-f9b8-471e-9062-e6610fd93400.png">

The results from w0 are still a work in progress, they turned out to be a bit tricky!

**Comment by dlanzieri** [comment]
Since our discussion and the fact we realized that the cosmological shift parameter varies with w0, Omega_m and sigma8, I'll close this issue!
