### ISSUE TITLE
Weird behavior with LogNormal_field for varying cosmologies

### ISSUE THREAD

**Issue by Justinezgh** [DifferentiableUniverseInitiative/sbi_lens#40]
Hi @EiffL and @dlanzieri, I checked the simulator (by looking at the power spectrum) for different cosmo params than the fiducials, and I got weird results: 
``` 
Omega_c: 0.24082552 
Omega_b: 0.03865506 
Sigma_8: 0.6434185
h_0: 0.70308214 
n_s: 0.88341194
w_0: -0.561326
```
![image](https://user-images.githubusercontent.com/72011736/233796136-9abfc303-78fb-4930-a501-4d0d4c9ed989.png)

You can have a look at the notebook [here](https://colab.research.google.com/drive/1YqrfViCFyhjxeroCqfjGs2Dwdjw89qnk?usp=sharing). 

What do you think?

**Comment by EiffL** [comment]
Important life lesson.... if you store parameters as a list instead of a structure like a dictionary... you can be 70% sure that you are going to create problems for yourself down the line...

Try the following instead for the last cell of your notebook:
```python
for i in range(20):
  # remember that  params_name = ['omega_c', 'omega_b', 'sigma_8', 'h_0', 'n_s', 'w_0']
  omega_c, omega_b, sigma_8, h_0, n_s, w_0 = store_params[i]
  obs_maps = store_mass_map[i]

  check_power_spectrum(
      20, 
      a, 
      b, 
      z0, 
      gal_per_arcmin2, 
      nbins, 
      omega_c,
      omega_b,
      h_0,
      n_s,
      sigma_8,
      w_0,
      obs_maps, 
      with_noise=False
  )
```
![image](https://user-images.githubusercontent.com/861591/233840740-14c9fad4-46d3-4bbc-bdaa-57a9b0a9e618.png)
